CREATE TABLE STUDENT_TBL(
    STUDENT_NO NUMBER PRIMARY KEY,
    STUDENT_NAME VARCHAR2(20) NOT NULL,
    STUDENT_TEL VARCHAR2(20),
    STUDENT_EMAIL VARCHAR2(40),
    STUDENT_ADDR VARCHAR2(200),
    REG_DATE DATE DEFAULT SYSDATE
);
SELECT * FROM STUDENT_TBL;

CREATE SEQUENCE STD_NO_SEQ;

INSERT INTO STUDENT_TBL VALUES(1,'일용자','010-0000-0000','KHUSER01@NAVER.COM','서울시',DEFAULT);
DELETE FROM STUDENT_TBL WHERE STUDENT_NAME='일용자';

SHOW USER;

INSERT INTO STUDENT_TBL
  		VALUES(STD_NO_SEQ.NEXTVAL,'1','1','1','1',DEFAULT);
        
        
SELECT * FROM STUDENT_TBL WHERE STUDENT_NO = 5;

SELECT * FROM TAB;

SELECT * FROM MEMBER_TBL;

SELECT * FROM MEMBER_TBL;

INSERT INTO MEMBER_TBL VALUES('khuser04','pass04','사용자',23,'khuser04@iei.or.kr','010-0101-0101','부산','M','취미',DEFAULT);

DESC MEMBER_TBL;
SELECT * FROM TAB;

