--KH계정 접속
--ALTER로 컬럼추가
ALTER TABLE DEPARTMENT
ADD (LNAME VARCHAR2(20));

DESC DEPARTMENT;

--ALTER로 컬럼수정
ALTER TABLE DEPARTMENT
MODIFY LNAME VARCHAR2(21);

--ALTER로 컬럼 삭제
ALTER TABLE DEPARTMENT
DROP COLUMN LNAME;

DESC DEPARTMENT;

--ALTER로 컬림 이름 변경
ALTER TABLE DEPARTMENT
ADD LNAME VARCHAR2(21);

DESC DEPARTMENT;

ALTER TABLE DEPARTMENT
RENAME COLUMN LNAME TO LOCATION_NAME;

DESC DEPARTMENT;

--테이블 명 변경을 위해 생성한 MEMBER테이블
CREATE TABLE MEMBER(
    MEMBER_ID VARCHAR2(20),
    MEMBER_PWD VARCHAR2(30),
    MAMBER_AGE NUMBER,
    MEMBER_DATE DATE
    );
    
--ALTER로 테이블 이름 변경
ALTER TABLE MEMBER RENAME TO WORKER;

DESC WORKER;
