CREATE TABLE NOTICE_TBL(
    NOTICE_NO NUMBER PRIMARY KEY,
    SUBJECT VARCHAR2(100) NOT NULL,
    CONTENTS VARCHAR2(1000) NOT NULL,
    MEMBER_ID VARCHAR2(20),
    REG_DATE DATE DEFAULT SYSDATE
);
DESC NOTICE_TBL;

/** 시퀀스 기본 설정으로 생성. 다 까먹음 **/
CREATE SEQUENCE SEQ_NOTICENO;  

INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICENO.NEXTVAL,'1','1','1',DEFAULT);
ROLLBACK;

SELECT * FROM NOTICE_TBL;
SELECT * FROM NOTICE_TBL WHERE NOTICE_NO = 1;

UPDATE NOTICE_TBL SET SUBJECT = '공지1이다.', CONTENTS = '공지1이다.' WHERE NOTICE_NO = 1 ;


SELECT SEQ_NOTICENO.NEXTVAL FROM DUAL;
SELECT SEQ_NOTICENO.CURRVAL FROM DUAL;

DELETE FROM NOTICE_TBL;

DROP SEQUENCE SEQ_NOTICENO;