--서브쿼리를 이용한 INSERT

CREATE TABLE EMP_01(
    EMP_ID NUMBER,
    EMP_NAME VARCHAR2(30),
    DEPT_TITLE VARCHAR2(20)
    );
SELECT * FROM EMP_01;

--서브쿼리를 이용하여 관련 데이터를 뽑아서 INSERT한다

INSERT INTO EMP_01
(   SELECT EMP_ID, EMP_NAME,DEPT_TITLE
    FROM EMPLOYEE
    LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
    );
    

--CREATE & SUBQUERY
--테이블 복사 -> 컬럼의 갯수, 컬럼명, 컬럼의 타입 .. 모두 복사 ->스키마라고 한다.
--테이블 스키마가 어떻게 되나? 라고 표현
DESC EMPLOYEE;
CREATE TABLE EMPLOYEE_COPY
AS SELECT EMP_ID, EMP_NAME, DEPT_CODE, HIRE_DATE  --*로 전체 복사가능, 예시를 위해 조금만 씀.
    FROM EMPLOYEE
    WHERE 1 = 0;   -- FALSE값
    
DESC EMPLOYEE_COPY;
SELECT * FROM EMPLOYEE_COPY;

CREATE TABLE EMP_MANAGER
AS SELECT EMP_ID, EMP_NAME, MANAGER_ID
FROM EMPLOYEE
WHERE 1 = 0;
SELECT * FROM EMP_MANAGER;
DELETE FROM EMP_MANAGER;

COMMIT;

--INSERT & SUBQUERY
--INSERT ALL > 한번에 2개 테이블에 데이터 넣기.
--[EMPLOYEE_COPY 테이블에 EMPLOYEE테이블의 부서 코드가 D2인 직원을 조회해
--사번, 이름, 소속부서, 입사일을 삽입하고, 
--EMP_MANAGER 테이블에 EMPLOYEE 테이블의 부서 코드가 D2인 직원의
--사번, 이름, 관리자사번을 조회해서 삽입하세요]

--한번의 쿼리로 두 개의 테이블에 넣음. 상황에 맞을 경우 사용하면 좋음.
INSERT ALL
INTO EMPLOYEE_COPY VALUES(EMP_ID, EMP_NAME, DEPT_CODE,HIRE_DATE)
INTO EMP_MANAGER VALUES(EMP_ID, EMP_NAME, MANAGER_ID)
SELECT EMP_ID, EMP_NAME, DEPT_CODE, HIRE_DATE, MANAGER_ID -- 두 테이블에 한번에 값을 넣을 때 필요한 컬럼을 다 입력해야한다.
FROM EMPLOYEE WHERE DEPT_CODE = 'D1';


--UPDATE & SUBQUERY
--억지스럽지만 쓸 수는 있는 케이스 소개
CREATE TABLE EMP_SALARY
AS SELECT EMP_ID, EMP_NAME, DEPT_CODE,SALARY,BONUS
FROM EMPLOYEE;

UPDATE EMP_SALARY
SET SALARY = (SELECT SALARY FROM EMP_SALARY WHERE EMP_NAME = '유재식'),
    BONUS = (SELECT BONUS FROM EMP_SALARY WHERE EMP_NAME = '유재식')
WHERE EMP_NAME = '하이유';

SELECT * FROM EMP_SALARY;

ROLLBACK;
