

CREATE TABLE MEMBER_TBL(
    MEMBER_ID VARCHAR2(20) PRIMARY KEY,
    MEMBER_PWD VARCHAR2(10) NOT NULL,
    MEMBEER_NAME VARCHAR2(10) NOT NULL,
    MEMBER_SSN NUMBER NOT NULL,
    MEMBER_ADDRESS VARCHAR2(50),
    MEMBER_PHONE VARCHAR2(12),
    MEMBER_EMAIL VARCHAR2(30)
    );
    
SELECT * FROM MEMBER_TBL;
DESC MEMBER_TBL;

COMMIT;

ALTER TABLE MEMBER_TBL MODIFY(
MEMBER_SSN VARCHAR(20));

ALTER TABLE MEMBER_TBL ADD(
JOIN_DATE DATE DEFAULT SYSDATE);

COMMIT;

ALTER TABLE MEMBER_TBL MODIFY(
MEMBER_PHONE VARCHAR2(20));

COMMIT;

SELECT * FROM MEMBER_TBL;

DESC MEMBER_TBL;

ALTER TABLE MEMBER_TBL RENAME COLUMN MEMBEER_NAME TO MEMBER_NAME;