INSERT INTO LOVER(LOVER_NAME, LOVER_PWD, LOVER_AGE,LOVER_DATA)
VALUES('khuser01','pass01',33,SYSDATE);
SELECT * FROM TAB;

INSERT INTO LOVER(LOVER_NAME,LOVER_PWD, LOVER_AGE,LOVER_DATA)
VALUES('khuser2','pass02',40,SYSDATE);

INSERT INTO LOVER VALUES('khuser3','pass03','22',SYSDATE);

SELECT LOVER_NAME, LOVER_PWD, lover_age, LOVER_DATA
FROM LOVER
--WHERE LOVER_NAME = 'khuser2';

DELETE
FROM LOVER  -- where를 안 쓰면 다~ 지워짐
WHERE LOVER_NAME = 'khuser3';

UPDATE LOVER
SET LOVER_NAME = null   -- 이러면 다~ 바뀜
WHERE LOVER_NAME = 'khuser01';

SELECT *
FROM LOVER;

UPDATE LOVER
SET LOVER_NAME = 'KHUSER01'
WHERE LOVER_NAME IS NULL;

SELECT *
FROM LOVER;
