
--테이블 생성 CREATE
CREATE TABLE EMP(EMPNO NUMBER,
    ENAME VARCHAR2(10),
    JOP VARCHAR2(9),
    MGR NUMBER,
    HIREDATE DATE,
    SAL NUMBER,
    COMM NUMBER,
    DEPTNO NUMBER);
    
CREATE TABLE DEPT(DEPTNO NUMBER,
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13));

CREATE TABLE BONUS(ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    SAL NUMBER,
    COMM NUMBER);

CREATE TABLE SALGRADE(GRADE NUMBER,
    LOSAL NUMBER,
    HISAL NUMBER);
    
SELECT * FROM TAB;

DESC EMP;